version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[palette]
    black="#272822"
    brown="#87875f"
    gray="#C0C0C0"
    gray2="#585858"
    gray3="#75715e"
    red="#ff0000"
    green="#87ff00"
    green2="#5fd700"
    orange="#ff5f00"
    yellow="#d7af00"
    blue="#00afff"
    blue2="#66d9ef"
    cyan="#a1efe4"
    purple="#ae81ff"
    white="#f8f8f2"

#[palette] Old
#    black="#272822"
#    gray="#75715e"
#    red="#f92672"
#    green="#a6e22e"
#    orange="#fd971f"
#    yellow="#ffd866"
#    blue="#66d9ef"
#    cyan="#a1efe4"
#    purple="#ae81ff"
#    white="#f8f8f2"

[[blocks]]
    type = "prompt"
    alignment = "left"
    newline = true

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground = "p:gray3"
        template = "╭─ "

    [[blocks.segments]]
        type = "os"
        style = "plain"
        foreground = "p:green"
        background = "transparent"
        template = "{{ if .WSL }}WSL at {{ end }}{{ .Icon }} "

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground = "p:gray"
        template = "with "

    [[blocks.segments]]
        type = "session"
        style = "plain"
        background = "transparent"
        foreground = "p:orange"
        template = "{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} "

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground = "p:gray"
        template = "in "

    [[blocks.segments]]
        type = "path"
        style = "plain"
        template = " {{ path .Path .Location }} "
        background = "transparent"
        foreground = "p:blue"

        [blocks.segments.properties]
            style = "full"

    [[blocks.segments]]
        type = "git"
        style = "plain"
        background = "transparent"
        foreground = "p:green"
        foreground_templates = [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:purple{{ end }}",
            "{{ if gt .Ahead 0 }}p:green{{ end }}",
            "{{ if gt .Behind 0 }}p:red{{ end }}"
        ]
        template = "{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }}{{ end }}{{ .HEAD }} {{ if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}"
        #template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

    [blocks.segments.properties]
        branch_max_length = 25
        fetch_status = true
        fetch_upstream_icon = true
        branch_ahead_icon = "⇡"
        branch_behind_icon = "⇣" 

[[blocks]]
    type = "prompt"
    alignment = "left"
    newline = true

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground = "p:gray3"
        template = "╰─"

    [[blocks.segments]]
        type = "root"
        style = "plain"
        background = "transparent"
        foreground = "p:red"
        template = "[ROOT] "

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground_templates = [
            "{{ if gt .Code 0 }}p:red{{ end }}",
            "{{ if eq .Code 0 }}p:green2{{ end }}"
        ]
        template = "❯"

[[blocks]]
    type = "rprompt"
    overflow = "hidden"

    [[blocks.segments]]
        type = "executiontime"
        style = "plain"
        background = "transparent"
        foreground = "p:yellow"
        template = "{{ div .Ms 1000 }}s"

        [blocks.segments.properties]
            threshold = 5000

[transient_prompt]
    background = "transparent"
    foreground_templates = [
        " {{if gt .Code 0}} p:red{{ end }}",
        " {{if eq .Code 0}} p:green2{{ end }}"
    ]
    template = "❯ "

