" Prep work
    " Create directories
        silent !mkdir ~/.cache/vim_backup > /dev/null 2>&1
        silent !mkdir ~/.cache/vim_undo > /dev/null 2>&1
        silent !mkdir ~/.cache/vim_swp > /dev/null 2>&1
    
    " Get options
        runtime! vimrc-plugins.vim
        "runtime! vimrc-statusline.vim
    
    " Set directories
        set backupdir=~/.cache/vim_backup/,/tmp//           " Specify backup dir
        set directory=~/.cache/vim_swp/,/tmp//              " Specify directory dir
        if has("persistent_undo")                           " Specify undo dir
            let target_path = expand('~/.cache/vim_undo')
            let &undodir=target_path
            set undofile
        endif

" VIM Options
    " Required
        filetype on                             " Enable type file detection
        filetype plugin on                      " Enable plugins and load plugin for the detected file type
        filetype indent on                      " Load an indent file for detected file type
        syntax on                               " Syntax highlighting
        colorscheme molokai                     " Specify a color scheme

        let mapleader="\<Space>"                " Leader, in this case, space

        "let g:markdown_folding=1               " Folds markdown automatically
        set encoding=UTF-8
        set foldmethod=marker                   " Default method is {{{ }}}
        set laststatus=2                        " Always show statusline
        set nocompatible
        set omnifunc=syntaxcomplete#Complete    " It ain't intellisense, only omnicomplete

        " Please ignore this files:
        set wildignore=*.jpg,*.mp4,*.zip,*.iso,*.pdf,*.png,*.png,*.tar,*.gz,*.bz2,*.tgz,*.db,*.exe,*.img,*.mp3,*.m4a,*.bmp,*.deb,*.rpm

    " Editor
        set backspace=indent,eol,start          " Proper backspace behavior
        set hidden                              " Possibility to have more than one unsaved buffers
        set incsearch                           " Incremental search, hit <CR > to stop
        set noshowmode                          " Makes the text below the bar disappear
        set number                              " Show line numbers
        set relativenumber                      " Show relative number from your cursor
        set ruler                               " Show line and cursor number of the cursor
        set showcmd                             " Display the incomplete commands in the bottom right-hand side of your screen
        set showmatch                           " Show search matches
        set wildmenu                            " Great command-line completion, use <Tab > to move around and <CR > to validate
        set wildmode=longest,list,full          " Autocompletion
        
        set textwidth=170                       " Wraps around 170 colummn
        set wrap                                " Line wrapping
        set linebreak                           " Break by word, not by character
        set colorcolumn=170

        "set cursorline                         " Sets a cursor horizontal line
        set cursorcolumn                        " Sets a cursor vertical line

        set autoindent                          " Minimal automatic indenting for any filetype
        set expandtab                           " Use spaces instead of tabs
        set shiftwidth=4                        " Make a tab equal to 4 spaces
        set smartindent                         " Enable smart autoindenting
        set smarttab                            " Enable smart tabs
        set tabstop=4                           " Make a tab equal to 4 spaces
        set scrolloff=15                        " Set a minimum number of lines to see above/above

        set splitbelow                          " Opens at bottom (instead of upper)
        set splitright                          " Opens at right (instead of left)

        set conceallevel=2                      " Conceal syntax (eg. markdown **bold** -> bold)

        runtime macros /matchit.vim             " Hit '%' on 'if' to jump to 'else'

" AutoCMD
    " Python
        autocmd FileType python nnoremap <buffer> <F9> :w<CR>:exec '!python3' shellescape(@%, 1)<CR>
    " Markdown
        autocmd FileType markdown nnoremap <buffer> <F9> :w<CR>:!okular %<CR><CR>
    " VIM
        "augroup numbertoggle
        "    autocmd!
        "    autocmd BufEnter,FocusGained,InsertLeave,WinEnter  * if &nu && mode() != "i"   | set rnu   | endif
        "    autocmd BufLeave,FocusLost,InsertEnter,WinLeave    * if &nu                    | set nornu | endif
        "augroup END

" Mappings
    " Function keys
        inoremap <F1>                   <C-X><Tab>
        nnoremap <silent><F2>           :Files<CR>
        nnoremap <silent><S-F2>         :Files %:p:h<CR>
        nnoremap <silent><F3>           :Goyo<CR>
        nnoremap <silent><F4>           :UndotreeToggle<CR>
        nnoremap <F5>                   :w!<CR>
        nnoremap <leader><F5>           :wq!<CR>
        nnoremap <silent><F6>           :Buffers<CR>
        "nnoremap <F7>                   :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
        nnoremap <S-F11>                :mksession! ${path_vimsessions}/current_session.vim<CR>
        nnoremap <leader><S-F11>        :source ${path_vimsessions}/current_session.vim<CR>
        nnoremap <silent><F12>          :sp ${path_dotrepo}/RTM.md<CR>

        :command -nargs=1 Mksw          :mks! ${path_vimsessions}/<args>.vim
        :command -nargs=1 Mksl          :source ${path_vimsessions}/<args>.vim

    " Colorschemes quick change
        nnoremap <silent><leader>cs     :colorscheme slate<CR>
        nnoremap <silent><leader>cj     :colorscheme jellybeans<CR>
        nnoremap <silent><leader>cm     :colorscheme molokai<CR>

    " Buffers
        nnoremap <leader><PageDown>     :bprevious<CR>
        nnoremap <leader><PageUp>       :bnext<CR>
        nnoremap <leader><Delete>       :bdelete<CR>
        nnoremap <leader><C-Delete>     :bdelete<space>
        nnoremap <leader><S-Delete>     :bwipeout<CR>

    " Split buffers
        nnoremap <leader>h              :sp<CR>
        nnoremap <leader>v              :vsp<CR>
        nnoremap <leader>H              :sb<space>
        nnoremap <leader>V              :vert sb<space>

    " Moving in windows/splits
        nnoremap <C-h>                  <C-w>h
        nnoremap <C-j>                  <C-w>j
        nnoremap <C-k>                  <C-w>k
        nnoremap <C-l>                  <C-w>l
        nnoremap <C-M-H>                <C-w>H
        nnoremap <C-M-J>                <C-w>J
        nnoremap <C-M-K>                <C-w>K
        nnoremap <C-M-L>                <C-w>L

    " Increase/decrease windows/splits size
        nnoremap L                      <C-w><
        nnoremap J                      <C-w>+
        nnoremap K                      <C-w>-
        nnoremap H                      <C-w>>

    " VIM Omnicomplete
        inoremap <C-j>                  <C-N>
        inoremap <C-k>                  <C-P>

    " QoL (shamelessly compiled from multiple sources)
        nnoremap <Leader>d              "_d
        vnoremap <Leader>d              "_d
        nnoremap <Leader>c              "_c
        vnoremap <Leader>c              "_c
        "nnoremap k                      kzz
        "nnoremap j                      jzz
        vnoremap J                      :m '>+1<CR>gv=gv
        vnoremap K                      :m '<-2<CR>gv=gv
        "nnoremap <C-d>                  <C-d>zz
        "nnoremap <C-u>                  <C-u>zz
        nnoremap Y                      y$
        "nnoremap <Leader>y              "+y
        "vnoremap <Leader>y              "+y
        "nnoremap <Leader>Y              "+Y
        nnoremap Q                      <nop>
        nnoremap <Leader>s              :%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>

    " Brackets
        "inoremap "                     ""<left>
        "inoremap '                     ''<left>
        "inoremap (                     ()<left>
        "inoremap [                     []<left>
        "inoremap {                     {}<left>
        "inoremap {<CR>                 {<CR>}<ESC>O
        "inoremap {;<CR>                {<CR>};<ESC>O

    " fzf-vim - Fuzzy Finder
        nnoremap <silent>gf             :GFiles<CR>
        nnoremap <silent>gc             :Commits<CR>
        nnoremap <silent>//             :BLines<CR>
        nnoremap <silent>f//            :BLines!<CR>
        nnoremap <silent>a//            :Lines<CR>

    " Toggles
        nnoremap <leader>ws             :ToggleWhitespace<CR>
        nnoremap <leader>wss            :ToggleStripWhitespaceOnSave<CR>
        "nnoremap <leader>ig             :IndentGuidesToggle<CR>    " This is already a default command

" Deprecated
        "nnoremap <leader>rp             :RainbowParentheses!!<CR>
