# TMUX autostart
if [ -n "${WT_SESSION}" ]; then
    export TMUX_TMPDIR='/tmp';
fi
if [ -z "$TMUX" ]; then
    (tmux attach -t BASE) || (tmux new -s BASE);
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if  [ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Exports
export TERM="xterm-256color"
export EDITOR=vim
export VISUAL=vim
export BAT_THEME="Monokai Extended"
export path_dotrepo="${HOME}/.dotfiles"
export path_vimsessions="${HOME}/.dotfiles/config/vim/sessions"

# Sources p10k
#   To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ ! -f "${path_dotrepo}/config/zsh/.p10k.zsh" ] || . "${path_dotrepo}/config/zsh/.p10k.zsh"
[ ! -f "${path_dotrepo}/config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme" ] || . "${path_dotrepo}/config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme"

# Sources linux
if [ -d "/etc/os-release/" ] ; then
    . /etc/os-release
# Sources  macOS
elif [ command -v sw_vers > /dev/null 2>&1 ] ; then
    ID="$(sw_vers -productName)"
fi
. "${path_dotrepo}/config/zsh/zshrc-plugins.zsh"
. "${path_dotrepo}/config/zsh/zshrc-alias.zsh"

# Lines configured by zsh-newuser-install
HISTFILE="${HOME}/.cache/.histfile"
HISTSIZE=10000
SAVEHIST=10000

# Vim keybindings
bindkey -v
export KEYTIMEOUT=1

# The following lines were added by compinstall
zstyle :compinstall filename "${HOME}/.zshrc"
autoload -Uz compinit
compinit

