# Oh My Posh
eval "$(oh-my-posh init zsh --config ${nmb_dotrepo}/config/ohmyposh/nmbrito_omp.toml)"

# ZSH history
    HISTFILE="${HOME}/.cache/.histfile"
    HISTSIZE=10000
    SAVEHIST=10000

    setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
    setopt SHARE_HISTORY             # Share history between all sessions.
    setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
    setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
    setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
    setopt HIST_SAVE_NO_DUPS         # 
    setopt HIST_FIND_NO_DUPS         # 

    setopt BANG_HIST                 # Treat the '!' character specially during expansion.
    setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.

# VIM bindings
    bindkey -v
    export KEYTIMEOUT=1

# Completion
    zstyle :compintall filename "${nmb_zshconf}/zshrc"
    autoload -U compinit && compinit

# Source alias
    . "${nmb_zshconf}/alias/zsh_alias.zsh"

    case ${ID} in
        "opensuse-tumbleweed")
            . "${nmb_zshconf}/alias/zsh_alias_opensuse.zsh"
            ;;
        "macOS")
            . "${nmb_zshconf}/alias/zsh_alias_macos.zsh"
            ;;
        *) ;;
    esac

    if [ ${wslsession} ]; then . "${nmb_zshconf}/alias/zsh_alias_wsl.zsh" ; fi

# Source plugins
    . "${nmb_zshconf}/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
    . "${nmb_zshconf}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
    . "${nmb_zshconf}/plugins/colored-man-pages/colored-man-pages.plugin.zsh"

# Source configs
    . "${nmb_zshconf}/config/zsh_config_fzf.zsh"

#/usr/local/share/zsh/site-functions
