#Uncomment if you want p10k back.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if  [ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]; then
  . "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# Sources p10k
#   To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ ! -f "${nmb_dotrepo}/config/zsh/.p10k.zsh" ] || . "${nmb_dotrepo}/config/zsh/.p10k.zsh"
[ ! -f "${nmb_dotrepo}/config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme" ] || . "${nmb_dotrepo}/config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme"

# Oh My Posh
#eval "$(oh-my-posh init zsh --config ${nmb_dotrepo}/config/ohmyposh/nmbrito.omp.toml)"

# ZSH history
    HISTFILE="${HOME}/.cache/.histfile"
    HISTSIZE=10000
    SAVEHIST=10000

    setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
    setopt SHARE_HISTORY             # Share history between all sessions.
    setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
    setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
    setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
    setopt HIST_SAVE_NO_DUPS         # 
    setopt HIST_FIND_NO_DUPS         # 

    setopt BANG_HIST                 # Treat the '!' character specially during expansion.
    setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.

# VIM bindings
    bindkey -v
    export KEYTIMEOUT=1

# Completion
    zstyle :compintall filename "${nmb_zshconf}/zshrc"
    autoload -U compinit && compinit

# Source alias
    if [ -f ${nmb_zshconf}/alias/zsh_alias.zsh ]; then
        . ${nmb_zshconf}/alias/zsh_alias.zsh
    fi
    if [ -f ${nmb_zshconf}/alias/zsh_alias_flatpak.zsh ]; then
        . ${nmb_zshconf}/alias/zsh_alias_flatpak.zsh
    fi

    case ${ID} in
        "opensuse-tumbleweed")
            if [ -f ${nmb_zshconf}/alias/zsh_alias_opensuse.zsh ]; then
                . ${nmb_zshconf}/alias/zsh_alias_opensuse.zsh
            fi
            ;;
        "macOS")
            if [ -f ${nmb_zshconf}/alias/zsh_alias_macos.zsh ]; then
                . ${nmb_zshconf}/alias/zsh_alias_macos.zsh
            fi
            ;;
    esac

    if [ ${wsl_Session} ]; then
        if [ -f ${nmb_zshconf}/alias/zsh_alias_wsl.zsh ]; then
            . ${nmb_zshconf}/alias/zsh_alias_wsl.zsh
        fi
    fi

# Source plugins
    [ -f "${nmb_zshconf}/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh" ] && . "${nmb_zshconf}/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
    [ -f "${nmb_zshconf}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh" ] && . "${nmb_zshconf}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
    [ -f "${nmb_zshconf}/plugins/colored-man-pages/colored-man-pages.plugin.zsh" ] && . "${nmb_zshconf}/plugins/colored-man-pages/colored-man-pages.plugin.zsh"

# Source configs
    [ -f "${nmb_zshconf}/config/zsh_config_fzf.zsh" ] && . "${nmb_zshconf}/config/zsh_config_fzf.zsh"

#/usr/local/share/zsh/site-functions
