#!/bin/sh

# Commands
distro_Name="Alma Linux"

install_Manager="dnf"
install_Install="${install_Manager} install -y"
install_InstallPattern=""

system_Update="${install_Manager} update"
system_Upgrade="${install_Manager} upgrade -y"
system_Clean="" 
system_Remove="" 

repo_Add=""
repo_Refresh=""
repo_Import=""
repo_GPGKeys=""

# Repositories
repository_GPGKeys=""
repository_NAME=""

# Packages
package_apache2=""
package_bat=""
package_blender=""
package_broadcom_wl=""
package_btop=""
package_build_base=""
package_build_essential=""
package_code=""
package_curl=""
package_discord=""
package_distrobox=""
package_exfat=""
package_eza=""
package_fastfetch=""
package_fd=""
package_fd_zsh_completion=""
package_ffmpeg=""
package_fprintd=""
package_fprintd_pam=""
package_fzf=""
package_fzf_tmux=""
package_fzf_zsh_completion=""
package_gcc=""
package_gdb=""
package_gimp=""
package_git="git"
package_git_doc=""
package_godot=""
package_htop=""
package_hyprland=""
package_hyprland_devel=""
package_inkscape=""
package_kdenlive=""
package_keepassxc=""
package_kicad=""
package_kid3=""
package_kitty=""
package_krita=""
package_kvantum_manager=""
package_lazygit=""
package_less=""
package_less_doc=""
package_libfprint=""
package_make=""
package_man_pages=""
package_mbpfan=""
package_mc=""
package_myspell_pt_PT=""
package_networkmanager_fortisslvpn=""
package_noto_fonts_cjk=""
package_onedrive=""
package_onedrive_completion_zsh=""
package_openfortivpn=""
package_openssh=""
package_oxygentheme=""
package_piper=""
package_plasma6_nm_fortisslvpn=""
package_podman=""
package_qbittorrent=""
package_rclone=""
package_rclone_zsh_completion=""
package_ripgrep=""
package_ripgrep_zsh_completion=""
package_shellcheck=""
package_steam=""
package_strawberry=""
package_tmux=""
package_valgrind=""
package_vifm=""
package_vifm_colors=""
package_vim=""
package_vim_data=""
package_vim_fzf=""
package_virt_manager=""
package_vlc=""
package_wsl_base=""
package_wsl_gui=""
package_wsl_systemd=""
package_xorgxrdp=""
package_xrdp=""
package_zsh=""

