#!/bin/sh

# Commands
distro_Name="openSUSE Tumbleweed"

install_Manager="zypper"
install_Command="${install_Manager} install -y --no-recommends"
install_Pattern="${install_Manager} install -y -t pattern"

system_Update="${install_Manager} up"
system_Upgrade="${install_Manager} dup -y"
system_Clean="" 
system_Remove="" 

repo_Add="${install_Manager} ar"
repo_Refresh="${install_Manager} ref"
repo_Import="rpm --import"
repo_GPGKeys="${install_Manager} --gpg-auto-import-keys ref"

# Repositories
repository_GPGKeys=""
repository_NAME=""

# Packages
package_apache2="apache2"
package_bat="bat"
package_blender="blender"
package_broadcom_wl="broadcom-wl"
package_btop="btop"
package_build_base=""
package_build_essential=""
package_code="code"
package_curl="curl"
package_discord="discord"
package_distrobox="distrobox"
package_exfat="exfatprogs"
package_eza="eza"
package_fastfetch="fastfetch"
package_fd="fd"
package_fd_zsh_completion="fd-zsh-completion"
package_ffmpeg="ffmpeg-7"
package_fprintd="fprintd"
package_fprintd_pam="fprintd-pam"
package_fzf="fzf"
package_fzf_tmux="fzf-tmux"
package_fzf_zsh_completion="fzf-zsh-completion"
package_gcc="gcc"
package_gdb="gdb"
package_gimp="gimp"
package_git="git"
package_git_doc=""
package_godot="godot"
package_htop="htop"
package_hyprland="hyprland"
package_hyprland_devel="hyprland-devel"
package_inkscape="inkscape"
package_kdenlive="kdenlive"
package_keepassxc="keepassxc"
package_kicad="kicad"
package_kid3="kid3"
package_kitty="kitty"
package_krita="krita"
package_kvantum_manager="kvantum-manager"
package_lazygit="lazygit"
package_less=""
package_less_doc=""
package_libfprint="libfprint"
package_make="make"
package_man_pages="man-pages"
package_mbpfan="mbpfan"
package_mc="mc"
package_myspell_pt_PT="myspell-pt_PT"
package_networkmanager_fortisslvpn="NetworkManager-fortisslvpn"
package_noto_fonts_cjk="google-noto-sans-cjk-fonts"
package_onedrive="onedrive"
package_onedrive_completion_zsh="onedrive-completion-zsh"
package_openfortivpn="openfortivpn"
package_openssh=""
package_oxygentheme="oxygen6"
package_piper="piper"
package_plasma6_nm_fortisslvpn="plasma6-nm-fortisslvpn"
package_podman="podman"
package_qbittorrent="qbittorrent"
package_rclone="rclone"
package_rclone_zsh_completion="rclone-zsh-completion"
package_ripgrep="ripgrep"
package_ripgrep_zsh_completion="ripgrep-zsh-completion"
package_shellcheck="ShellCheck"
package_steam="steam"
package_strawberry="strawberry"
package_tmux="tmux"
package_valgrind="valgrind"
package_vifm="vifm"
package_vifm_colors="vifm-colors"
package_vim="vim"
package_vim_data="vim-data"
package_vim_fzf="vim-fzf"
package_virt_manager="virt-manager"
package_vlc="vlc"
package_wsl_base="wsl_base"
package_wsl_gui="wsl_gui"
package_wsl_systemd="wsl_systemd"
package_xorgxrdp="xorgxrdp"
package_xrdp="xrdp"
package_zsh="zsh"

