#!/bin/sh

# Commands
distro_Name="openSUSE Tumbleweed"

package_Manager="zypper"

package_Install="${package_Manager} install"
package_InstallAuto="${package_Manager} install -y"
package_InstallPattern="${package_Manager} -t pattern"

system_Update="${package_Manager} up"
system_Upgrade="${package_Manager} dup"
system_UpgradeAuto="${package_Manager} dup -y"
system_Clean="" 
system_CleanAuto="" 
system_Remove="" 
system_RemoveAuto="" 

repo_Add="${package_Manager} ar"
repo_Refresh="${package_Manager} ref"
repo_Import="rpm --import"
repo_AutoGPGKeys="zypper --gpg-auto-import-keys ref"

# Repositories
gpgkey_microsoft="https://packages.microsoft.com/keys/microsoft.asc"
gpgkey_librewolf="https://rpm.librewolf.net/pubkey.gpg"

repository_vscode="https://packages.microsoft.com/yumrepos/vscode vscode"
repository_librewolf="https://rpm.librewolf.net librewolf"
repository_broadcom_wl="https://download.opensuse.org/repositories/home:Sauerland:hardware/openSUSE_Tumbleweed/home:Sauerland:hardware.repo"

# Packages
binary_apache2="apache2"
binary_bat="bat"
binary_blender="blender"
binary_broadcom_wl="broadcom-wl"
binary_btop="btop"
binary_build_base=""
binary_build_essential=""
binary_code="code"
binary_curl="curl"
binary_discord="discord"
binary_exfat="exfatprogs"
binary_eza="eza"
binary_fastfetch="fastfetch"
binary_fd="fd"
binary_fd_zsh_completion="fd-zsh-completion"
binary_ffmpeg="ffmpeg-7"
binary_fprintd="fprintd"
binary_fprintd_pam="fprintd-pam"
binary_fzf="fzf"
binary_fzf_tmux="fzf-tmux"
binary_fzf_zsh_completion="fzf-zsh-completion"
binary_gcc="gcc"
binary_gdb="gdb"
binary_gimp="gimp"
binary_git_doc=""
binary_godot="godot"
binary_htop="htop"
binary_hyprland="hyprland"
binary_hyprland_devel="hyprland-devel"
binary_inkscape="inkscape"
binary_kdenlive="kdenlive"
binary_keepassxc="keepassxc"
binary_kicad="kicad"
binary_kid3="kid3"
binary_kitty="kitty"
binary_krita="krita"
binary_kvantum_manager="kvantum-manager"
binary_lazygit="lazygit"
binary_less=""
binary_less_doc=""
binary_libfprint="libfprint"
binary_make="make"
binary_man_pages="man-pages"
binary_mbpfan="mbpfan"
binary_mc="mc"
binary_myspell_pt_PT="myspell-pt_PT"
binary_networkmanager_fortisslvpn="NetworkManager-fortisslvpn"
binary_ohmyposh=$(curl -s $url_OhMyPosh | bash -s -- -d ${HOME}/.local/bin)
binary_onedrive="onedrive"
binary_onedrive_completion_zsh="onedrive-completion-zsh"
binary_openfortivpn="openfortivpn"
binary_openssh=""
binary_oxygentheme="oxygen6"
binary_plasma6_nm_fortisslvpn="plasma6-nm-fortisslvpn"
binary_qbittorrent="qbittorrent"
binary_ripgrep="ripgrep"
binary_ripgrep_zsh_completion="ripgrep-zsh-completion"
binary_shellcheck="ShellCheck"
binary_strawberry="strawberry"
binary_tmux="tmux"
binary_valgrind="valgrind"
binary_vifm="vifm"
binary_vifm_colors="vifm-colors"
binary_vim="vim"
binary_vim_data="vim-data"
binary_vim_fzf="vim-fzf"
binary_virt_manager="virt-manager"
binary_vlc="vlc"
binary_wsl_base="wsl_base"
binary_wsl_gui="wsl_gui"
binary_wsl_systemd="wsl_systemd"
binary_xorgxrdp="xorgxrdp"
binary_xrdp="xrdp"
binary_zsh="zsh"
